# Wallet Watcher Configuration File
# This file contains the necessary settings for the watcher script to connect to Bitcoin Core and Firebase Cloud Messaging (FCM).

### Firebase Cloud Messaging Settings Section
[fcm]
# The base URL for the FCM API.
api_url = https://fcm.googleapis.com/v1/projects
# The specific API operation to perform (sending a message).
api_operation = messages:send
# Your Firebase project ID. You can find this in the Firebase console.
project_id = <FCM Project ID>
# The FCM notification channel ID. Used for Android notification grouping and settings.
channel_id = walletwatcher_fcm_channel
# The FCM registration token obtained from your Android device. This uniquely identifies the device for notifications.
token_key = <FCM token from Android device>

### Bitcoin Wallet Settings Section
[bitcoin]
## Bitcoin Core RPC Connection Details
# The IP address of your Bitcoin Core RPC server. This is often '127.0.0.1' (localhost) or the IP of a remote server.
rpc_host = 10.0.0.1
# The port number of your Bitcoin Core RPC server (default is 8332).
rpc_port = 8332

## Bitcoin Core RPC Authentication Credentials
# The username for authenticating with the Bitcoin Core RPC server. Set in your bitcoin.conf file.
rpc_user = <Bitcoin Core RPC username>
# The password for authenticating with the Bitcoin Core RPC server. Set in your bitcoin.conf file.
rpc_password = <Bitcoin Core RPC password>

## Wallet Settings
# The name of the Bitcoin Core wallet to be used by the watcher. This wallet will be loaded if exists or created automatically.
wallet_name = watcherwallet

## Descriptor Settings (Used to Watch Specific Addresses)
# The extended public key (xpub) of the Bitcoin wallet you want to watch.
xpub = <xpub############>
# The address type used in the descriptor. 'wpkh' for native segwit, 'sh-wpkh' for wrapped segwit, etc.
address_type = wpkh
# The master fingerprint of the hardware wallet or key from which the xpub was derived.
master_fingerprint = d34db33f
# The derivation path used to generate the xpub.
derivation_path = 44h/0h/0h
# The range of addresses to generate and watch (e.g., 10000 addresses).
descriptor_range = 10000
# The timestamp (Unix epoch) from which to rescan the wallet for transactions. Older transactions will be ignored.
rescan_timestamp = 1500000000
